import { Command } from './types';

export const INITIAL_COMMANDS: Command[] = [
  // Git - Avancé
  { id: 'git-1', command: 'git checkout -b <branch-name>', description: 'Créer et basculer sur une nouvelle branche', example: 'git checkout -b feature/ui', category: 'Git', tags: ['branch', 'flow'] },
  { id: 'git-2', command: 'git commit --amend -m "message"', description: 'Modifier le dernier commit', category: 'Git', tags: ['commit', 'fix'] },
  { id: 'git-3', command: 'git reset --hard HEAD~1', description: 'Annuler le dernier commit et supprimer les changements', category: 'Git', tags: ['reset', 'destructive'] },
  { id: 'git-4', command: 'git push origin --delete <branch-name>', description: 'Supprimer une branche distante', category: 'Git', tags: ['branch', 'remote'] },
  { id: 'git-5', command: 'git stash push -m "description"', description: 'Mettre de côté les changements actuels', category: 'Git', tags: ['stash'] },
  { id: 'git-6', command: 'git log --oneline --graph --all', description: 'Afficher l\'historique en graphe condensé', category: 'Git', tags: ['log'] },
  { id: 'git-7', command: 'git rebase -i HEAD~3', description: 'Rebase interactif des 3 derniers commits', category: 'Git', tags: ['rebase', 'interactive'] },
  { id: 'git-8', command: 'git cherry-pick <commit-hash>', description: 'Appliquer un commit spécifique', category: 'Git', tags: ['cherry-pick'] },
  { id: 'git-9', command: 'git bisect start', description: 'Démarrer le bisect pour trouver un bug', category: 'Git', tags: ['bisect', 'debug'] },
  { id: 'git-10', command: 'git reflog', description: 'Afficher l\'historique complet des références', category: 'Git', tags: ['reflog', 'history'] },
  { id: 'git-11', command: 'git clean -fd', description: 'Supprimer les fichiers non suivis', category: 'Git', tags: ['clean', 'untracked'] },
  { id: 'git-12', command: 'git submodule update --init --recursive', description: 'Initialiser et mettre à jour les sous-modules', category: 'Git', tags: ['submodule'] },
  { id: 'git-13', command: 'git filter-branch --tree-filter "rm -f file.txt" HEAD', description: 'Supprimer un fichier de tout l\'historique', category: 'Git', tags: ['filter-branch', 'history'] },
  { id: 'git-14', command: 'git worktree add ../feature-branch feature-branch', description: 'Créer un worktree pour une branche', category: 'Git', tags: ['worktree'] },
  { id: 'git-15', command: 'git blame file.txt', description: 'Voir qui a modifié chaque ligne', category: 'Git', tags: ['blame', 'annotate'] },

  // Docker - Avancé
  { id: 'docker-1', command: 'docker-compose up -d', description: 'Démarrer les conteneurs en arrière-plan', category: 'Docker', tags: ['run', 'compose'] },
  { id: 'docker-2', command: 'docker ps -a', description: 'Lister tous les conteneurs (actifs et inactifs)', category: 'Docker', tags: ['list'] },
  { id: 'docker-3', command: 'docker exec -it <container> /bin/bash', description: 'Ouvrir un terminal dans un conteneur', category: 'Docker', tags: ['exec', 'terminal'] },
  { id: 'docker-4', command: 'docker system prune -a', description: 'Nettoyer tout le système Docker inutilisé', category: 'Docker', tags: ['cleanup'] },
  { id: 'docker-5', command: 'docker build -t <name> .', description: 'Construire une image à partir d\'un Dockerfile', category: 'Docker', tags: ['build'] },
  { id: 'docker-6', command: 'docker run -d -p 8080:80 --name web nginx', description: 'Démarrer nginx avec port mapping', category: 'Docker', tags: ['run', 'port'] },
  { id: 'docker-7', command: 'docker logs -f <container>', description: 'Suivre les logs d\'un conteneur', category: 'Docker', tags: ['logs'] },
  { id: 'docker-8', command: 'docker network create my-network', description: 'Créer un réseau Docker', category: 'Docker', tags: ['network'] },
  { id: 'docker-9', command: 'docker volume create my-volume', description: 'Créer un volume Docker', category: 'Docker', tags: ['volume'] },
  { id: 'docker-10', command: 'docker-compose down -v', description: 'Arrêter et supprimer les volumes', category: 'Docker', tags: ['compose', 'cleanup'] },
  { id: 'docker-11', command: 'docker stats', description: 'Afficher les statistiques des conteneurs', category: 'Docker', tags: ['monitoring'] },
  { id: 'docker-12', command: 'docker inspect <container>', description: 'Inspecter un conteneur en détail', category: 'Docker', tags: ['inspect'] },
  { id: 'docker-13', command: 'docker save -o image.tar <image>', description: 'Exporter une image en fichier', category: 'Docker', tags: ['export'] },
  { id: 'docker-14', command: 'docker load -i image.tar', description: 'Importer une image depuis un fichier', category: 'Docker', tags: ['import'] },
  { id: 'docker-15', command: 'docker tag <source> <target>', description: 'Tagger une image Docker', category: 'Docker', tags: ['tag'] },

  // Laravel - Avancé
  { id: 'laravel-1', command: 'php artisan make:controller <Name>', description: 'Créer un contrôleur', category: 'Laravel', tags: ['artisan', 'make'] },
  { id: 'laravel-2', command: 'php artisan migrate:refresh --seed', description: 'Réinitialiser la DB et lancer les seeders', category: 'Laravel', tags: ['db', 'migrate'] },
  { id: 'laravel-3', command: 'php artisan list', description: 'Lister toutes les commandes Artisan disponibles', category: 'Laravel', tags: ['help'] },
  { id: 'laravel-4', command: 'php artisan make:middleware <Name>', description: 'Créer un middleware', category: 'Laravel', tags: ['make'] },
  { id: 'laravel-5', command: 'php artisan make:model <Model> -m', description: 'Créer un modèle avec migration', category: 'Laravel', tags: ['model', 'migration'] },
  { id: 'laravel-6', command: 'php artisan make:factory <Factory>', description: 'Créer une factory', category: 'Laravel', tags: ['factory', 'testing'] },
  { id: 'laravel-7', command: 'php artisan tinker', description: 'Ouvrir le REPL Laravel', category: 'Laravel', tags: ['tinker', 'interactive'] },
  { id: 'laravel-8', command: 'php artisan route:list', description: 'Lister toutes les routes', category: 'Laravel', tags: ['routes'] },
  { id: 'laravel-9', command: 'php artisan make:job <Job>', description: 'Créer un job', category: 'Laravel', tags: ['job', 'queue'] },
  { id: 'laravel-10', command: 'php artisan queue:work', description: 'Démarrer le worker de queues', category: 'Laravel', tags: ['queue', 'worker'] },
  { id: 'laravel-11', command: 'php artisan make:event <Event>', description: 'Créer un événement', category: 'Laravel', tags: ['event'] },
  { id: 'laravel-12', command: 'php artisan make:listener <Listener>', description: 'Créer un listener', category: 'Laravel', tags: ['listener'] },
  { id: 'laravel-13', command: 'php artisan make:policy <Policy>', description: 'Créer une politique', category: 'Laravel', tags: ['policy', 'authorization'] },
  { id: 'laravel-14', command: 'php artisan make:resource <Resource>', description: 'Créer une ressource API', category: 'Laravel', tags: ['api', 'resource'] },
  { id: 'laravel-15', command: 'php artisan optimize:clear', description: 'Vider tous les caches', category: 'Laravel', tags: ['cache', 'optimize'] },

  // Linux - Avancé
  { id: 'linux-1', command: 'ls -larth', description: 'Lister les fichiers avec détails et taille humaine', category: 'Linux', tags: ['files'] },
  { id: 'linux-2', command: 'find . -name "*.log" -delete', description: 'Trouver et supprimer tous les fichiers .log', category: 'Linux', tags: ['search', 'delete'] },
  { id: 'linux-3', command: 'top', description: 'Afficher les processus système en temps réel', category: 'Linux', tags: ['system'] },
  { id: 'linux-4', command: 'chmod +x <file>', description: 'Rendre un fichier exécutable', category: 'Linux', tags: ['permission'] },
  { id: 'linux-5', command: 'grep -r "pattern" /path', description: 'Rechercher un motif récursivement', category: 'Linux', tags: ['search', 'grep'] },
  { id: 'linux-6', command: 'tar -czf archive.tar.gz directory/', description: 'Compresser un répertoire', category: 'Linux', tags: ['archive', 'compress'] },
  { id: 'linux-7', command: 'tar -xzf archive.tar.gz', description: 'Extraire une archive tar.gz', category: 'Linux', tags: ['archive', 'extract'] },
  { id: 'linux-8', command: 'rsync -avz source/ destination/', description: 'Synchroniser des répertoires', category: 'Linux', tags: ['sync', 'backup'] },
  { id: 'linux-9', command: 'crontab -e', description: 'Éditer les tâches cron', category: 'Linux', tags: ['cron', 'schedule'] },
  { id: 'linux-10', command: 'netstat -tulpn', description: 'Afficher les connexions réseau', category: 'Linux', tags: ['network'] },
  { id: 'linux-11', command: 'df -h', description: 'Afficher l\'espace disque', category: 'Linux', tags: ['disk', 'space'] },
  { id: 'linux-12', command: 'du -sh *', description: 'Afficher la taille des répertoires', category: 'Linux', tags: ['disk', 'size'] },
  { id: 'linux-13', command: 'ps aux | grep process', description: 'Rechercher un processus', category: 'Linux', tags: ['process', 'search'] },
  { id: 'linux-14', command: 'kill -9 <pid>', description: 'Forcer l\'arrêt d\'un processus', category: 'Linux', tags: ['kill', 'process'] },
  { id: 'linux-15', command: 'sudo systemctl restart service', description: 'Redémarrer un service systemd', category: 'Linux', tags: ['systemd', 'service'] },

  // Python / Django - Avancé
  { id: 'django-1', command: 'python manage.py makemigrations', description: 'Préparer les migrations', category: 'Django', tags: ['db'] },
  { id: 'django-2', command: 'python manage.py shell', description: 'Ouvrir le shell Python interactif Django', category: 'Django', tags: ['interactive'] },
  { id: 'django-3', command: 'python manage.py createsuperuser', description: 'Créer un administrateur', category: 'Django', tags: ['admin'] },
  { id: 'django-4', command: 'python manage.py runserver 0.0.0.0:8000', description: 'Démarrer le serveur de développement', category: 'Django', tags: ['server', 'dev'] },
  { id: 'django-5', command: 'python manage.py collectstatic', description: 'Collecter les fichiers statiques', category: 'Django', tags: ['static'] },
  { id: 'django-6', command: 'python manage.py test', description: 'Lancer les tests', category: 'Django', tags: ['testing'] },
  { id: 'django-7', command: 'python manage.py migrate', description: 'Appliquer les migrations', category: 'Django', tags: ['db', 'migrate'] },
  { id: 'django-8', command: 'python manage.py flush', description: 'Vider la base de données', category: 'Django', tags: ['db', 'flush'] },
  { id: 'django-9', command: 'python manage.py check', description: 'Vérifier la configuration du projet', category: 'Django', tags: ['check', 'config'] },
  { id: 'django-10', command: 'python manage.py dumpdata > data.json', description: 'Exporter les données en JSON', category: 'Django', tags: ['export', 'data'] },
  { id: 'django-11', command: 'python manage.py loaddata data.json', description: 'Importer des données depuis JSON', category: 'Django', tags: ['import', 'data'] },
  { id: 'django-12', command: 'python manage.py showmigrations', description: 'Afficher l\'état des migrations', category: 'Django', tags: ['migrations', 'status'] },
  { id: 'django-13', command: 'python manage.py sqlmigrate app migration', description: 'Afficher le SQL d\'une migration', category: 'Django', tags: ['sql', 'migration'] },
  { id: 'django-14', command: 'python manage.py createsuperuser --noinput', description: 'Créer un admin sans interaction', category: 'Django', tags: ['admin', 'automation'] },
  { id: 'django-15', command: 'python manage.py shell_plus', description: 'Shell Django avec extensions', category: 'Django', tags: ['shell', 'extensions'] },

  // Node.js / npm - Avancé
  { id: 'node-1', command: 'npm list -g --depth=0', description: 'Lister les packages installés globalement', category: 'Node', tags: ['npm'] },
  { id: 'node-2', command: 'npm audit fix', description: 'Corriger les vulnérabilités de sécurité', category: 'Node', tags: ['security', 'audit'] },
  { id: 'node-3', command: 'npm outdated', description: 'Afficher les packages obsolètes', category: 'Node', tags: ['update', 'outdated'] },
  { id: 'node-4', command: 'npm cache clean --force', description: 'Vider le cache npm', category: 'Node', tags: ['cache', 'clean'] },
  { id: 'node-5', command: 'nvm install 18.17.0', description: 'Installer une version spécifique de Node', category: 'Node', tags: ['nvm', 'version'] },
  { id: 'node-6', command: 'nvm use 18.17.0', description: 'Utiliser une version spécifique de Node', category: 'Node', tags: ['nvm', 'switch'] },
  { id: 'node-7', command: 'npm run build', description: 'Construire le projet pour production', category: 'Node', tags: ['build', 'production'] },
  { id: 'node-8', command: 'npm test -- --coverage', description: 'Lancer les tests avec couverture', category: 'Node', tags: ['test', 'coverage'] },
  { id: 'node-9', command: 'npm pack', description: 'Créer un package .tgz', category: 'Node', tags: ['package', 'distribution'] },
  { id: 'node-10', command: 'npm link', description: 'Lier un package localement', category: 'Node', tags: ['link', 'development'] },
  { id: 'node-11', command: 'node --inspect app.js', description: 'Démarrer le débogueur Node', category: 'Node', tags: ['debug', 'inspect'] },
  { id: 'node-12', command: 'pm2 start app.js', description: 'Démarrer une application avec PM2', category: 'Node', tags: ['pm2', 'process'] },
  { id: 'node-13', command: 'pm2 monit', description: 'Monitorer les processus PM2', category: 'Node', tags: ['pm2', 'monitoring'] },
  { id: 'node-14', command: 'npm ls --depth=0', description: 'Lister les dépendances directes', category: 'Node', tags: ['dependencies', 'list'] },
  { id: 'node-15', command: 'npm prune', description: 'Supprimer les packages non utilisés', category: 'Node', tags: ['cleanup', 'dependencies'] },

  // React - Avancé
  { id: 'react-1', command: 'npx create-react-app <name>', description: 'Initialiser un nouveau projet React', category: 'React', tags: ['init'] },
  { id: 'react-2', command: 'npm run eject', description: 'Éjecter de Create React App', category: 'React', tags: ['eject', 'config'] },
  { id: 'react-3', command: 'npm run test:coverage', description: 'Tests avec couverture de code', category: 'React', tags: ['test', 'coverage'] },
  { id: 'react-4', command: 'npx create-next-app@latest', description: 'Créer une app Next.js', category: 'React', tags: ['nextjs', 'init'] },
  { id: 'react-5', command: 'npm run build:analyze', description: 'Analyser le bundle de production', category: 'React', tags: ['bundle', 'analyze'] },
  { id: 'react-6', command: 'npx storybook init', description: 'Initialiser Storybook', category: 'React', tags: ['storybook', 'components'] },
  { id: 'react-7', command: 'npm run lint:fix', description: 'Corriger automatiquement les erreurs ESLint', category: 'React', tags: ['lint', 'fix'] },
  { id: 'react-8', command: 'npx create-react-app --template typescript', description: 'Créer React avec TypeScript', category: 'React', tags: ['typescript', 'init'] },
  { id: 'react-9', command: 'npm run test -- --watchAll=false', description: 'Tests sans mode watch', category: 'React', tags: ['test', 'ci'] },
  { id: 'react-10', command: 'npx react-native init <AppName>', description: 'Initialiser React Native', category: 'React', tags: ['react-native', 'mobile'] },
  { id: 'react-11', command: 'npm run build:stats', description: 'Générer les statistiques du build', category: 'React', tags: ['build', 'stats'] },
  { id: 'react-12', command: 'npx create-react-app --use-npm', description: 'Créer React avec npm', category: 'React', tags: ['init', 'npm'] },
  { id: 'react-13', command: 'npm run start:https', description: 'Démarrer en HTTPS', category: 'React', tags: ['https', 'security'] },
  { id: 'react-14', command: 'npx shadcn-ui@latest init', description: 'Initialiser shadcn/ui', category: 'React', tags: ['shadcn', 'ui'] },
  { id: 'react-15', command: 'npm run dev:network', description: 'Développement accessible sur réseau', category: 'React', tags: ['network', 'development'] },

  // Kubernetes - Avancé
  { id: 'k8s-1', command: 'kubectl get pods', description: 'Lister les pods du cluster', category: 'Kubernetes', tags: ['pods', 'list'] },
  { id: 'k8s-2', command: 'kubectl apply -f <file.yaml>', description: 'Appliquer une configuration YAML', category: 'Kubernetes', tags: ['apply'] },
  { id: 'k8s-3', command: 'kubectl get services', description: 'Lister les services', category: 'Kubernetes', tags: ['services'] },
  { id: 'k8s-4', command: 'kubectl describe pod <pod-name>', description: 'Décrire un pod en détail', category: 'Kubernetes', tags: ['describe', 'pod'] },
  { id: 'k8s-5', command: 'kubectl logs -f <pod-name>', description: 'Suivre les logs d\'un pod', category: 'Kubernetes', tags: ['logs'] },
  { id: 'k8s-6', command: 'kubectl delete deployment <name>', description: 'Supprimer un deployment', category: 'Kubernetes', tags: ['delete', 'deployment'] },
  { id: 'k8s-7', command: 'kubectl exec -it <pod> -- /bin/bash', description: 'Exécuter un shell dans un pod', category: 'Kubernetes', tags: ['exec', 'shell'] },
  { id: 'k8s-8', command: 'kubectl get nodes', description: 'Lister les nœuds du cluster', category: 'Kubernetes', tags: ['nodes'] },
  { id: 'k8s-9', command: 'kubectl scale deployment <name> --replicas=3', description: 'Scaler un deployment', category: 'Kubernetes', tags: ['scale', 'replicas'] },
  { id: 'k8s-10', command: 'kubectl top pods', description: 'Afficher l\'utilisation des ressources', category: 'Kubernetes', tags: ['monitoring', 'resources'] },
  { id: 'k8s-11', command: 'kubectl get ingress', description: 'Lister les ingress', category: 'Kubernetes', tags: ['ingress'] },
  { id: 'k8s-12', command: 'kubectl port-forward <pod> 8080:80', description: 'Forward de port vers un pod', category: 'Kubernetes', tags: ['port-forward'] },
  { id: 'k8s-13', command: 'kubectl config use-context <context>', description: 'Changer de contexte k8s', category: 'Kubernetes', tags: ['config', 'context'] },
  { id: 'k8s-14', command: 'kubectl get all', description: 'Lister toutes les ressources', category: 'Kubernetes', tags: ['list', 'all'] },
  { id: 'k8s-15', command: 'kubectl apply -k <directory>', description: 'Appliquer avec Kustomize', category: 'Kubernetes', tags: ['kustomize'] },

  // SQL - Avancé
  { id: 'sql-1', command: 'SELECT * FROM table LIMIT 10;', description: 'Sélectionner les 10 premières lignes', category: 'SQL', tags: ['query'] },
  { id: 'sql-2', command: 'CREATE INDEX idx_name ON table(column);', description: 'Créer un index', category: 'SQL', tags: ['index', 'performance'] },
  { id: 'sql-3', command: 'EXPLAIN SELECT * FROM table;', description: 'Analyser un plan d\'exécution', category: 'SQL', tags: ['explain', 'performance'] },
  { id: 'sql-4', command: 'INSERT INTO table (col1, col2) VALUES (val1, val2);', description: 'Insérer des données', category: 'SQL', tags: ['insert'] },
  { id: 'sql-5', command: 'UPDATE table SET col = value WHERE condition;', description: 'Mettre à jour des données', category: 'SQL', tags: ['update'] },
  { id: 'sql-6', command: 'DELETE FROM table WHERE condition;', description: 'Supprimer des données', category: 'SQL', tags: ['delete'] },
  { id: 'sql-7', command: 'CREATE TABLE table (id INT PRIMARY KEY, name VARCHAR(100));', description: 'Créer une table', category: 'SQL', tags: ['create', 'table'] },
  { id: 'sql-8', command: 'DROP TABLE table;', description: 'Supprimer une table', category: 'SQL', tags: ['drop', 'table'] },
  { id: 'sql-9', command: 'ALTER TABLE table ADD COLUMN new_col TYPE;', description: 'Ajouter une colonne', category: 'SQL', tags: ['alter', 'column'] },
  { id: 'sql-10', command: 'SELECT COUNT(*) FROM table;', description: 'Compter les lignes', category: 'SQL', tags: ['count', 'aggregate'] },
  { id: 'sql-11', command: 'SELECT * FROM table ORDER BY col DESC LIMIT 1;', description: 'Dernier enregistrement', category: 'SQL', tags: ['order', 'limit'] },
  { id: 'sql-12', command: 'SELECT DISTINCT col FROM table;', description: 'Valeurs distinctes', category: 'SQL', tags: ['distinct'] },
  { id: 'sql-13', command: 'SELECT * FROM table WHERE col LIKE "%pattern%";', description: 'Recherche avec pattern', category: 'SQL', tags: ['like', 'search'] },
  { id: 'sql-14', command: 'SELECT * FROM table1 JOIN table2 ON table1.id = table2.id;', description: 'Jointure entre tables', category: 'SQL', tags: ['join'] },
  { id: 'sql-15', command: 'BACKUP DATABASE db_name TO DISK = \'path\';', description: 'Sauvegarder la base', category: 'SQL', tags: ['backup'] },

  // AWS - Avancé
  { id: 'aws-1', command: 'aws s3 ls', description: 'Lister les buckets S3', category: 'AWS', tags: ['s3', 'list'] },
  { id: 'aws-2', command: 'aws ec2 describe-instances', description: 'Lister les instances EC2', category: 'AWS', tags: ['ec2', 'instances'] },
  { id: 'aws-3', command: 'aws lambda list-functions', description: 'Lister les fonctions Lambda', category: 'AWS', tags: ['lambda', 'functions'] },
  { id: 'aws-4', command: 'aws rds describe-db-instances', description: 'Lister les instances RDS', category: 'AWS', tags: ['rds', 'database'] },
  { id: 'aws-5', command: 'aws cloudformation deploy --template-file template.yaml', description: 'Déployer CloudFormation', category: 'AWS', tags: ['cloudformation', 'deploy'] },
  { id: 'aws-6', command: 'aws s3 cp file.txt s3://bucket/', description: 'Copier un fichier vers S3', category: 'AWS', tags: ['s3', 'upload'] },
  { id: 'aws-7', command: 'aws ec2 start-instances --instance-ids i-12345', description: 'Démarrer une instance EC2', category: 'AWS', tags: ['ec2', 'start'] },
  { id: 'aws-8', command: 'aws iam list-users', description: 'Lister les utilisateurs IAM', category: 'AWS', tags: ['iam', 'users'] },
  { id: 'aws-9', command: 'aws elbv2 describe-load-balancers', description: 'Lister les load balancers', category: 'AWS', tags: ['elb', 'load-balancer'] },
  { id: 'aws-10', command: 'aws sns publish --topic-arn arn --message "Hello"', description: 'Publier un message SNS', category: 'AWS', tags: ['sns', 'publish'] },
  { id: 'aws-11', command: 'aws dynamodb list-tables', description: 'Lister les tables DynamoDB', category: 'AWS', tags: ['dynamodb', 'tables'] },
  { id: 'aws-12', command: 'aws cloudwatch get-metric-statistics', description: 'Obtenir des métriques CloudWatch', category: 'AWS', tags: ['cloudwatch', 'metrics'] },
  { id: 'aws-13', command: 'aws eks list-clusters', description: 'Lister les clusters EKS', category: 'AWS', tags: ['eks', 'kubernetes'] },
  { id: 'aws-14', command: 'aws s3 sync local/ s3://bucket/', description: 'Synchroniser avec S3', category: 'AWS', tags: ['s3', 'sync'] },
  { id: 'aws-15', command: 'aws configure set region us-west-2', description: 'Configurer la région AWS', category: 'AWS', tags: ['config', 'region'] },

  // Go - Avancé
  { id: 'go-1', command: 'go mod tidy', description: 'Nettoyer et mettre à jour les dépendances', category: 'Go', tags: ['deps'] },
  { id: 'go-2', command: 'go run main.go', description: 'Exécuter un programme Go', category: 'Go', tags: ['run'] },
  { id: 'go-3', command: 'go build -o app .', description: 'Compiler un exécutable', category: 'Go', tags: ['build'] },
  { id: 'go-4', command: 'go test ./...', description: 'Lancer tous les tests', category: 'Go', tags: ['test'] },
  { id: 'go-5', command: 'go install github.com/tool@latest', description: 'Installer un outil Go', category: 'Go', tags: ['install', 'tool'] },
  { id: 'go-6', command: 'go vet ./...', description: 'Analyser le code statique', category: 'Go', tags: ['vet', 'analyze'] },
  { id: 'go-7', command: 'go fmt ./...', description: 'Formater le code Go', category: 'Go', tags: ['format'] },
  { id: 'go-8', command: 'go mod download', description: 'Télécharger les dépendances', category: 'Go', tags: ['deps', 'download'] },
  { id: 'go-9', command: 'go test -cover ./...', description: 'Tests avec couverture', category: 'Go', tags: ['test', 'coverage'] },
  { id: 'go-10', command: 'go mod init module-name', description: 'Initialiser un module Go', category: 'Go', tags: ['module', 'init'] },
  { id: 'go-11', command: 'go generate ./...', description: 'Générer le code', category: 'Go', tags: ['generate'] },
  { id: 'go-12', command: 'go version', description: 'Afficher la version Go', category: 'Go', tags: ['version'] },
  { id: 'go-13', command: 'go env GOPATH', description: 'Afficher le GOPATH', category: 'Go', tags: ['env', 'gopath'] },
  { id: 'go-14', command: 'go list -m all', description: 'Lister tous les modules', category: 'Go', tags: ['modules', 'list'] },
  { id: 'go-15', command: 'go test -race ./...', description: 'Tests avec détection de race condition', category: 'Go', tags: ['test', 'race'] },

  // Rust - Avancé
  { id: 'rust-1', command: 'cargo build --release', description: 'Compiler le projet pour la production', category: 'Rust', tags: ['build'] },
  { id: 'rust-2', command: 'cargo run', description: 'Exécuter le projet', category: 'Rust', tags: ['run'] },
  { id: 'rust-3', command: 'cargo test', description: 'Lancer les tests', category: 'Rust', tags: ['test'] },
  { id: 'rust-4', command: 'cargo check', description: 'Vérifier le code sans compiler', category: 'Rust', tags: ['check'] },
  { id: 'rust-5', command: 'cargo clippy', description: 'Analyser avec Clippy', category: 'Rust', tags: ['clippy', 'lint'] },
  { id: 'rust-6', command: 'cargo fmt', description: 'Formater le code Rust', category: 'Rust', tags: ['format'] },
  { id: 'rust-7', command: 'cargo doc --open', description: 'Générer et ouvrir la documentation', category: 'Rust', tags: ['documentation'] },
  { id: 'rust-8', command: 'cargo clean', description: 'Nettoyer les artefacts de build', category: 'Rust', tags: ['clean'] },
  { id: 'rust-9', command: 'cargo update', description: 'Mettre à jour les dépendances', category: 'Rust', tags: ['deps', 'update'] },
  { id: 'rust-10', command: 'cargo install cargo-watch', description: 'Installer cargo-watch', category: 'Rust', tags: ['install', 'tool'] },
  { id: 'rust-11', command: 'cargo watch -x run', description: 'Surveiller et recompiler', category: 'Rust', tags: ['watch', 'dev'] },
  { id: 'rust-12', command: 'cargo bench', description: 'Lancer les benchmarks', category: 'Rust', tags: ['benchmark'] },
  { id: 'rust-13', command: 'cargo tree', description: 'Afficher l\'arbre des dépendances', category: 'Rust', tags: ['deps', 'tree'] },
  { id: 'rust-14', command: 'cargo audit', description: 'Auditer les dépendances', category: 'Rust', tags: ['security', 'audit'] },
  { id: 'rust-15', command: 'cargo expand', description: 'Développer les macros', category: 'Rust', tags: ['macros', 'expand'] },

  // Vue.js - Avancé
  { id: 'vue-1', command: 'npm create vue@latest', description: 'Créer un projet Vue 3', category: 'Vue', tags: ['init', 'create'] },
  { id: 'vue-2', command: 'npm run dev', description: 'Démarrer le serveur de développement', category: 'Vue', tags: ['dev', 'server'] },
  { id: 'vue-3', command: 'npm run build', description: 'Construire pour production', category: 'Vue', tags: ['build', 'production'] },
  { id: 'vue-4', command: 'npm run test:unit', description: 'Lancer les tests unitaires', category: 'Vue', tags: ['test', 'unit'] },
  { id: 'vue-5', command: 'npm run lint', description: 'Vérifier le code avec ESLint', category: 'Vue', tags: ['lint'] },
  { id: 'vue-6', command: 'vue add router', description: 'Ajouter Vue Router', category: 'Vue', tags: ['router', 'plugin'] },
  { id: 'vue-7', command: 'vue add vuex', description: 'Ajouter Vuex', category: 'Vue', tags: ['vuex', 'plugin'] },
  { id: 'vue-8', command: 'npm run preview', description: 'Prévisualiser le build de production', category: 'Vue', tags: ['preview', 'build'] },
  { id: 'vue-9', command: 'vue ui', description: 'Lancer l\'interface graphique Vue CLI', category: 'Vue', tags: ['ui', 'cli'] },
  { id: 'vue-10', command: 'npm run test:e2e', description: 'Lancer les tests E2E', category: 'Vue', tags: ['test', 'e2e'] },
  { id: 'vue-11', command: 'vue inspect', description: 'Inspecter la configuration webpack', category: 'Vue', tags: ['inspect', 'config'] },
  { id: 'vue-12', command: 'npm run build:modern', description: 'Build avec polyfills modernes', category: 'Vue', tags: ['build', 'modern'] },
  { id: 'vue-13', command: 'vue create --preset preset-name', description: 'Créer avec un preset', category: 'Vue', tags: ['preset', 'create'] },
  { id: 'vue-14', command: 'npm run serve:ssr', description: 'Démarrer le serveur SSR', category: 'Vue', tags: ['ssr', 'server'] },
  { id: 'vue-15', command: 'vue add i18n', description: 'Ajouter l\'internationalisation', category: 'Vue', tags: ['i18n', 'plugin'] },

  // Angular - Avancé
  { id: 'angular-1', command: 'ng new <project-name>', description: 'Créer un nouveau projet Angular', category: 'Angular', tags: ['init', 'create'] },
  { id: 'angular-2', command: 'ng serve', description: 'Démarrer le serveur de développement', category: 'Angular', tags: ['serve', 'dev'] },
  { id: 'angular-3', command: 'ng build', description: 'Construire pour production', category: 'Angular', tags: ['build', 'production'] },
  { id: 'angular-4', command: 'ng generate component <name>', description: 'Générer un composant', category: 'Angular', tags: ['generate', 'component'] },
  { id: 'angular-5', command: 'ng generate service <name>', description: 'Générer un service', category: 'Angular', tags: ['generate', 'service'] },
  { id: 'angular-6', command: 'ng generate module <name>', description: 'Générer un module', category: 'Angular', tags: ['generate', 'module'] },
  { id: 'angular-7', command: 'ng test', description: 'Lancer les tests unitaires', category: 'Angular', tags: ['test', 'unit'] },
  { id: 'angular-8', command: 'ng e2e', description: 'Lancer les tests E2E', category: 'Angular', tags: ['test', 'e2e'] },
  { id: 'angular-9', command: 'ng lint', description: 'Vérifier le code avec ESLint', category: 'Angular', tags: ['lint'] },
  { id: 'angular-10', command: 'ng add @angular/material', description: 'Ajouter Angular Material', category: 'Angular', tags: ['material', 'ui'] },
  { id: 'angular-11', command: 'ng build --configuration production', description: 'Build de production optimisé', category: 'Angular', tags: ['build', 'production'] },
  { id: 'angular-12', command: 'ng update @angular/core', description: 'Mettre à jour Angular', category: 'Angular', tags: ['update', 'core'] },
  { id: 'angular-13', command: 'ng generate guard <name>', description: 'Générer un guard', category: 'Angular', tags: ['generate', 'guard'] },
  { id: 'angular-14', command: 'ng generate interceptor <name>', description: 'Générer un interceptor HTTP', category: 'Angular', tags: ['generate', 'interceptor'] },
  { id: 'angular-15', command: 'ng analytics off', description: 'Désactiver les analytics Angular', category: 'Angular', tags: ['analytics', 'privacy'] },

  // Ruby / Rails - Avancé
  { id: 'rails-1', command: 'rails new <app-name>', description: 'Créer une nouvelle app Rails', category: 'Rails', tags: ['init', 'create'] },
  { id: 'rails-2', command: 'rails server', description: 'Démarrer le serveur Rails', category: 'Rails', tags: ['server', 'dev'] },
  { id: 'rails-3', command: 'rails generate controller <Controller>', description: 'Générer un contrôleur', category: 'Rails', tags: ['generate', 'controller'] },
  { id: 'rails-4', command: 'rails generate model <Model>', description: 'Générer un modèle', category: 'Rails', tags: ['generate', 'model'] },
  { id: 'rails-5', command: 'rails db:migrate', description: 'Appliquer les migrations', category: 'Rails', tags: ['db', 'migrate'] },
  { id: 'rails-6', command: 'rails console', description: 'Ouvrir la console Rails', category: 'Rails', tags: ['console', 'interactive'] },
  { id: 'rails-7', command: 'rails generate scaffold <Resource>', description: 'Générer un scaffold complet', category: 'Rails', tags: ['generate', 'scaffold'] },
  { id: 'rails-8', command: 'rails test', description: 'Lancer les tests', category: 'Rails', tags: ['test'] },
  { id: 'rails-9', command: 'rails routes', description: 'Afficher les routes', category: 'Rails', tags: ['routes'] },
  { id: 'rails-10', command: 'rails db:seed', description: 'Alimenter la base de données', category: 'Rails', tags: ['db', 'seed'] },
  { id: 'rails-11', command: 'rails generate migration <name>', description: 'Générer une migration', category: 'Rails', tags: ['generate', 'migration'] },
  { id: 'rails-12', command: 'rails db:rollback', description: 'Annuler la dernière migration', category: 'Rails', tags: ['db', 'rollback'] },
  { id: 'rails-13', command: 'rails generate job <Job>', description: 'Générer un job', category: 'Rails', tags: ['generate', 'job'] },
  { id: 'rails-14', command: 'rails generate mailer <Mailer>', description: 'Générer un mailer', category: 'Rails', tags: ['generate', 'mailer'] },
  { id: 'rails-15', command: 'rails assets:precompile', description: 'Précompiler les assets', category: 'Rails', tags: ['assets', 'compile'] },

  // PHP / Symfony - Avancé
  { id: 'symfony-1', command: 'symfony new <project-name>', description: 'Créer un nouveau projet Symfony', category: 'Symfony', tags: ['init', 'create'] },
  { id: 'symfony-2', command: 'symfony server:start', description: 'Démarrer le serveur Symfony', category: 'Symfony', tags: ['server', 'dev'] },
  { id: 'symfony-3', command: 'php bin/console make:controller <Controller>', description: 'Créer un contrôleur', category: 'Symfony', tags: ['make', 'controller'] },
  { id: 'symfony-4', command: 'php bin/console make:entity <Entity>', description: 'Créer une entité', category: 'Symfony', tags: ['make', 'entity'] },
  { id: 'symfony-5', command: 'php bin/console doctrine:migrations:migrate', description: 'Appliquer les migrations Doctrine', category: 'Symfony', tags: ['doctrine', 'migrate'] },
  { id: 'symfony-6', command: 'php bin/console cache:clear', description: 'Vider le cache', category: 'Symfony', tags: ['cache', 'clear'] },
  { id: 'symfony-7', command: 'composer install', description: 'Installer les dépendances', category: 'Symfony', tags: ['composer', 'install'] },
  { id: 'symfony-8', command: 'php bin/console make:form <Form>', description: 'Créer un formulaire', category: 'Symfony', tags: ['make', 'form'] },
  { id: 'symfony-9', command: 'php bin/console debug:router', description: 'Déboguer les routes', category: 'Symfony', tags: ['debug', 'router'] },
  { id: 'symfony-10', command: 'php bin/console make:middleware <Middleware>', description: 'Créer un middleware', category: 'Symfony', tags: ['make', 'middleware'] },
  { id: 'symfony-11', command: 'php bin/console doctrine:schema:update --force', description: 'Mettre à jour le schéma de la BDD', category: 'Symfony', tags: ['doctrine', 'schema'] },
  { id: 'symfony-12', command: 'php bin/console make:fixture <Fixture>', description: 'Créer une fixture', category: 'Symfony', tags: ['make', 'fixture'] },
  { id: 'symfony-13', command: 'php bin/console server:dump', description: 'Dumper le serveur', category: 'Symfony', tags: ['server', 'dump'] },
  { id: 'symfony-14', command: 'php bin/console make:validator <Validator>', description: 'Créer un validateur', category: 'Symfony', tags: ['make', 'validator'] },
  { id: 'symfony-15', command: 'php bin/console debug:container', description: 'Déboguer le conteneur DI', category: 'Symfony', tags: ['debug', 'container'] },

  // Flutter / Dart - Avancé
  { id: 'flutter-1', command: 'flutter create <app-name>', description: 'Créer une nouvelle app Flutter', category: 'Flutter', tags: ['init', 'create'] },
  { id: 'flutter-2', command: 'flutter run', description: 'Exécuter l\'app Flutter', category: 'Flutter', tags: ['run'] },
  { id: 'flutter-3', command: 'flutter build apk', description: 'Construire l\'APK Android', category: 'Flutter', tags: ['build', 'android'] },
  { id: 'flutter-4', command: 'flutter build ios', description: 'Construire pour iOS', category: 'Flutter', tags: ['build', 'ios'] },
  { id: 'flutter-5', command: 'flutter doctor', description: 'Vérifier l\'environnement Flutter', category: 'Flutter', tags: ['doctor', 'check'] },
  { id: 'flutter-6', command: 'flutter pub get', description: 'Télécharger les dépendances', category: 'Flutter', tags: ['pub', 'deps'] },
  { id: 'flutter-7', command: 'flutter upgrade', description: 'Mettre à jour Flutter', category: 'Flutter', tags: ['upgrade'] },
  { id: 'flutter-8', command: 'flutter test', description: 'Lancer les tests', category: 'Flutter', tags: ['test'] },
  { id: 'flutter-9', command: 'flutter clean', description: 'Nettoyer le projet', category: 'Flutter', tags: ['clean'] },
  { id: 'flutter-10', command: 'flutter packages pub run build_runner build', description: 'Générer le code', category: 'Flutter', tags: ['build', 'runner'] },
  { id: 'flutter-11', command: 'flutter analyze', description: 'Analyser le code', category: 'Flutter', tags: ['analyze'] },
  { id: 'flutter-12', command: 'flutter devices', description: 'Lister les appareils', category: 'Flutter', tags: ['devices'] },
  { id: 'flutter-13', command: 'flutter emulators', description: 'Lister les émulateurs', category: 'Flutter', tags: ['emulators'] },
  { id: 'flutter-14', command: 'flutter build web', description: 'Construire pour le web', category: 'Flutter', tags: ['build', 'web'] },
  { id: 'flutter-15', command: 'flutter install', description: 'Installer sur un appareil', category: 'Flutter', tags: ['install'] },

  // Swift / iOS - Avancé
  { id: 'swift-1', command: 'swift build', description: 'Compiler un projet Swift', category: 'Swift', tags: ['build'] },
  { id: 'swift-2', command: 'swift test', description: 'Lancer les tests Swift', category: 'Swift', tags: ['test'] },
  { id: 'swift-3', command: 'swift run', description: 'Exécuter un programme Swift', category: 'Swift', tags: ['run'] },
  { id: 'swift-4', command: 'swift package init', description: 'Initialiser un package Swift', category: 'Swift', tags: ['package', 'init'] },
  { id: 'swift-5', command: 'xcodebuild -scheme <scheme> build', description: 'Construire avec Xcode', category: 'Swift', tags: ['xcodebuild', 'build'] },
  { id: 'swift-6', command: 'xcodebuild test', description: 'Tester avec Xcode', category: 'Swift', tags: ['xcodebuild', 'test'] },
  { id: 'swift-7', command: 'swift format', description: 'Formater le code Swift', category: 'Swift', tags: ['format'] },
  { id: 'swift-8', command: 'swiftlint', description: 'Analyser avec SwiftLint', category: 'Swift', tags: ['lint'] },
  { id: 'swift-9', command: 'carthage update', description: 'Mettre à jour les dépendances Carthage', category: 'Swift', tags: ['carthage', 'deps'] },
  { id: 'swift-10', command: 'pod install', description: 'Installer les CocoaPods', category: 'Swift', tags: ['cocoapods', 'deps'] },
  { id: 'swift-11', command: 'swift package generate-xcodeproj', description: 'Générer un projet Xcode', category: 'Swift', tags: ['xcode', 'generate'] },
  { id: 'swift-12', command: 'xcrun simctl list', description: 'Lister les simulateurs iOS', category: 'Swift', tags: ['simulator', 'list'] },
  { id: 'swift-13', command: 'fastlane beta', description: 'Déployer avec Fastlane', category: 'Swift', tags: ['fastlane', 'deploy'] },
  { id: 'swift-14', command: 'swift package resolve', description: 'Résoudre les dépendances', category: 'Swift', tags: ['deps', 'resolve'] },
  { id: 'swift-15', command: 'swift repl', description: 'Lancer le REPL Swift', category: 'Swift', tags: ['repl', 'interactive'] },

  // Kotlin / Android - Avancé
  { id: 'kotlin-1', command: './gradlew build', description: 'Construire un projet Android', category: 'Kotlin', tags: ['gradle', 'build'] },
  { id: 'kotlin-2', command: './gradlew test', description: 'Lancer les tests', category: 'Kotlin', tags: ['gradle', 'test'] },
  { id: 'kotlin-3', command: './gradlew assembleDebug', description: 'Construire l\'APK de debug', category: 'Kotlin', tags: ['gradle', 'apk'] },
  { id: 'kotlin-4', command: './gradlew assembleRelease', description: 'Construire l\'APK de release', category: 'Kotlin', tags: ['gradle', 'release'] },
  { id: 'kotlin-5', command: 'adb install app-debug.apk', description: 'Installer un APK sur un appareil', category: 'Kotlin', tags: ['adb', 'install'] },
  { id: 'kotlin-6', command: 'adb logcat', description: 'Afficher les logs Android', category: 'Kotlin', tags: ['adb', 'logs'] },
  { id: 'kotlin-7', command: './gradlew connectedAndroidTest', description: 'Tests Android connectés', category: 'Kotlin', tags: ['gradle', 'android-test'] },
  { id: 'kotlin-8', command: 'kotlinc HelloWorld.kt -include-runtime -d HelloWorld.jar', description: 'Compiler Kotlin en JAR', category: 'Kotlin', tags: ['kotlinc', 'compile'] },
  { id: 'kotlin-9', command: 'java -jar HelloWorld.jar', description: 'Exécuter un JAR Kotlin', category: 'Kotlin', tags: ['java', 'run'] },
  { id: 'kotlin-10', command: './gradlew lint', description: 'Analyser le code avec Lint', category: 'Kotlin', tags: ['gradle', 'lint'] },
  { id: 'kotlin-11', command: 'adb devices', description: 'Lister les appareils Android', category: 'Kotlin', tags: ['adb', 'devices'] },
  { id: 'kotlin-12', command: './gradlew clean', description: 'Nettoyer le projet', category: 'Kotlin', tags: ['gradle', 'clean'] },
  { id: 'kotlin-13', command: 'adb shell am start <package>/<activity>', description: 'Démarrer une app Android', category: 'Kotlin', tags: ['adb', 'start'] },
  { id: 'kotlin-14', command: './gradlew dependencies', description: 'Afficher les dépendances', category: 'Kotlin', tags: ['gradle', 'deps'] },
  { id: 'kotlin-15', command: 'adb uninstall <package>', description: 'Désinstaller une app Android', category: 'Kotlin', tags: ['adb', 'uninstall'] },

  // DevOps - Avancé
  { id: 'devops-1', command: 'terraform init', description: 'Initialiser Terraform', category: 'DevOps', tags: ['terraform', 'init'] },
  { id: 'devops-2', command: 'terraform plan', description: 'Planifier les changements Terraform', category: 'DevOps', tags: ['terraform', 'plan'] },
  { id: 'devops-3', command: 'terraform apply', description: 'Appliquer les changements Terraform', category: 'DevOps', tags: ['terraform', 'apply'] },
  { id: 'devops-4', command: 'ansible-playbook playbook.yml', description: 'Exécuter un playbook Ansible', category: 'DevOps', tags: ['ansible', 'playbook'] },
  { id: 'devops-5', command: 'docker-compose -f docker-compose.prod.yml up -d', description: 'Docker Compose production', category: 'DevOps', tags: ['docker-compose', 'prod'] },
  { id: 'devops-6', command: 'helm install <release> <chart>', description: 'Installer un chart Helm', category: 'DevOps', tags: ['helm', 'install'] },
  { id: 'devops-7', command: 'vagrant up', description: 'Démarrer une VM Vagrant', category: 'DevOps', tags: ['vagrant', 'up'] },
  { id: 'devops-8', command: 'packer build template.json', description: 'Construire une image Packer', category: 'DevOps', tags: ['packer', 'build'] },
  { id: 'devops-9', command: 'consul members', description: 'Lister les membres Consul', category: 'DevOps', tags: ['consul', 'cluster'] },
  { id: 'devops-10', command: 'nomad status', description: 'Afficher le statut Nomad', category: 'DevOps', tags: ['nomad', 'status'] },
  { id: 'devops-11', command: 'vault kv get secret/path', description: 'Lire un secret Vault', category: 'DevOps', tags: ['vault', 'secret'] },
  { id: 'devops-12', command: 'jenkins-cli build <job>', description: 'Lancer un build Jenkins', category: 'DevOps', tags: ['jenkins', 'build'] },
  { id: 'devops-13', command: 'gitlab-ci-multi-runner exec docker <job>', description: 'Exécuter un job GitLab CI', category: 'DevOps', tags: ['gitlab-ci', 'runner'] },
  { id: 'devops-14', command: 'circleci local execute --job <job>', description: 'Exécuter un job CircleCI localement', category: 'DevOps', tags: ['circleci', 'local'] },
  { id: 'devops-15', command: 'travis lint', description: 'Valider la configuration Travis CI', category: 'DevOps', tags: ['travis', 'lint'] },

  // Monitoring - Avancé
  { id: 'monitoring-1', command: 'prometheus --config.file=prometheus.yml', description: 'Démarrer Prometheus', category: 'Monitoring', tags: ['prometheus', 'start'] },
  { id: 'monitoring-2', command: 'grafana-cli plugins install <plugin>', description: 'Installer un plugin Grafana', category: 'Monitoring', tags: ['grafana', 'plugin'] },
  { id: 'monitoring-3', command: 'elasticsearch -E cluster.name=mycluster', description: 'Démarrer Elasticsearch', category: 'Monitoring', tags: ['elasticsearch', 'start'] },
  { id: 'monitoring-4', command: 'kibana -e http://localhost:9200', description: 'Démarrer Kibana', category: 'Monitoring', tags: ['kibana', 'start'] },
  { id: 'monitoring-5', command: 'logstash -f logstash.conf', description: 'Démarrer Logstash', category: 'Monitoring', tags: ['logstash', 'start'] },
  { id: 'monitoring-6', command: 'jaeger-all-in-one', description: 'Démarrer Jaeger tracing', category: 'Monitoring', tags: ['jaeger', 'tracing'] },
  { id: 'monitoring-7', command: 'zipkin serve', description: 'Démarrer Zipkin tracing', category: 'Monitoring', tags: ['zipkin', 'tracing'] },
  { id: 'monitoring-8', command: 'nagios -v /etc/nagios/nagios.cfg', description: 'Vérifier la config Nagios', category: 'Monitoring', tags: ['nagios', 'config'] },
  { id: 'monitoring-9', command: 'zabbix_server -c /etc/zabbix/zabbix_server.conf', description: 'Démarrer Zabbix server', category: 'Monitoring', tags: ['zabbix', 'server'] },
  { id: 'monitoring-10', command: 'sentry-cli send-dif', description: 'Envoyer des debug info Sentry', category: 'Monitoring', tags: ['sentry', 'debug'] },
  { id: 'monitoring-11', command: 'newrelic-admin install-config', description: 'Configurer New Relic', category: 'Monitoring', tags: ['newrelic', 'config'] },
  { id: 'monitoring-12', command: 'datadog-agent start', description: 'Démarrer l\'agent Datadog', category: 'Monitoring', tags: ['datadog', 'agent'] },
  { id: 'monitoring-13', command: 'telegraf --config telegraf.conf', description: 'Démarrer Telegraf', category: 'Monitoring', tags: ['telegraf', 'start'] },
  { id: 'monitoring-14', command: 'influxd run', description: 'Démarrer InfluxDB', category: 'Monitoring', tags: ['influxdb', 'start'] },
  { id: 'monitoring-15', command: 'grafana-server --config=grafana.ini', description: 'Démarrer Grafana server', category: 'Monitoring', tags: ['grafana', 'server'] },

  // Sécurité - Avancé
  { id: 'security-1', command: 'nmap -sV -p 1-65535 target', description: 'Scanner tous les ports avec versions', category: 'Security', tags: ['nmap', 'scan'] },
  { id: 'security-2', command: 'nikto -h http://target', description: 'Scanner web avec Nikto', category: 'Security', tags: ['nikto', 'web-scan'] },
  { id: 'security-3', command: 'sqlmap -u "http://target/page?id=1"', description: 'Tester les injections SQL', category: 'Security', tags: ['sqlmap', 'sql-injection'] },
  { id: 'security-4', command: 'burpsuite', description: 'Démarrer Burp Suite', category: 'Security', tags: ['burpsuite', 'proxy'] },
  { id: 'security-5', command: 'wireshark', description: 'Démarrer Wireshark', category: 'Security', tags: ['wireshark', 'packet-capture'] },
  { id: 'security-6', command: 'metasploit', description: 'Démarrer Metasploit Framework', category: 'Security', tags: ['metasploit', 'exploit'] },
  { id: 'security-7', command: 'john --wordlist=wordlist.txt hash.txt', description: 'Casser des mots de passe avec John', category: 'Security', tags: ['john', 'password-crack'] },
  { id: 'security-8', command: 'hashcat -m 0 hash.txt wordlist.txt', description: 'Casser des hashes avec Hashcat', category: 'Security', tags: ['hashcat', 'hash-crack'] },
  { id: 'security-9', command: 'gpg --encrypt --recipient user file.txt', description: 'Chiffrer un fichier avec GPG', category: 'Security', tags: ['gpg', 'encrypt'] },
  { id: 'security-10', command: 'openssl enc -aes-256-cbc -in file.txt -out file.enc', description: 'Chiffrer avec OpenSSL AES', category: 'Security', tags: ['openssl', 'encrypt'] },
  { id: 'security-11', command: 'ssh-keygen -t rsa -b 4096', description: 'Générer une clé SSH RSA', category: 'Security', tags: ['ssh', 'keygen'] },
  { id: 'security-12', command: 'certbot --nginx -d domain.com', description: 'Obtenir un certificat Let\'s Encrypt', category: 'Security', tags: ['certbot', 'ssl'] },
  { id: 'security-13', command: 'fail2ban-client status sshd', description: 'Vérifier le statut Fail2Ban SSH', category: 'Security', tags: ['fail2ban', 'ssh'] },
  { id: 'security-14', command: 'ufw enable', description: 'Activer le firewall UFW', category: 'Security', tags: ['ufw', 'firewall'] },
  { id: 'security-15', command: 'lynis audit system', description: 'Auditer la sécurité du système', category: 'Security', tags: ['lynis', 'audit'] },

  // Machine Learning / Data Science - Avancé
  { id: 'ml-1', command: 'jupyter notebook', description: 'Démarrer Jupyter Notebook', category: 'ML', tags: ['jupyter', 'notebook'] },
  { id: 'ml-2', command: 'jupyter lab', description: 'Démarrer JupyterLab', category: 'ML', tags: ['jupyterlab', 'ide'] },
  { id: 'ml-3', command: 'pip install tensorflow', description: 'Installer TensorFlow', category: 'ML', tags: ['tensorflow', 'install'] },
  { id: 'ml-4', command: 'pip install torch', description: 'Installer PyTorch', category: 'ML', tags: ['pytorch', 'install'] },
  { id: 'ml-5', command: 'python train.py', description: 'Entraîner un modèle', category: 'ML', tags: ['train', 'model'] },
  { id: 'ml-6', command: 'python predict.py', description: 'Faire des prédictions', category: 'ML', tags: ['predict', 'inference'] },
  { id: 'ml-7', command: 'mlflow ui', description: 'Démarrer MLflow UI', category: 'ML', tags: ['mlflow', 'tracking'] },
  { id: 'ml-8', command: 'tensorboard --logdir logs/', description: 'Démarrer TensorBoard', category: 'ML', tags: ['tensorboard', 'visualization'] },
  { id: 'ml-9', command: 'python -m pytest tests/', description: 'Lancer les tests ML', category: 'ML', tags: ['pytest', 'test'] },
  { id: 'ml-10', command: 'conda create -n env python=3.9', description: 'Créer un environnement Conda', category: 'ML', tags: ['conda', 'environment'] },
  { id: 'ml-11', command: 'conda activate env', description: 'Activer un environnement Conda', category: 'ML', tags: ['conda', 'activate'] },
  { id: 'ml-12', command: 'pip freeze > requirements.txt', description: 'Générer requirements.txt', category: 'ML', tags: ['pip', 'requirements'] },
  { id: 'ml-13', command: 'python -m spacy download en_core_web_sm', description: 'Télécharger un modèle spaCy', category: 'ML', tags: ['spacy', 'model'] },
  { id: 'ml-14', command: 'scikit-learn', description: 'Importer scikit-learn', category: 'ML', tags: ['scikit-learn', 'library'] },
  { id: 'ml-15', command: 'pandas.read_csv("data.csv")', description: 'Lire un CSV avec pandas', category: 'ML', tags: ['pandas', 'csv'] },

  // Blockchain / Crypto - Avancé
  { id: 'blockchain-1', command: 'truffle init', description: 'Initialiser un projet Truffle', category: 'Blockchain', tags: ['truffle', 'init'] },
  { id: 'blockchain-2', command: 'truffle compile', description: 'Compiler les contrats Truffle', category: 'Blockchain', tags: ['truffle', 'compile'] },
  { id: 'blockchain-3', command: 'truffle migrate', description: 'Déployer les contrats', category: 'Blockchain', tags: ['truffle', 'deploy'] },
  { id: 'blockchain-4', command: 'ganache-cli', description: 'Démarrer Ganache blockchain locale', category: 'Blockchain', tags: ['ganache', 'local'] },
  { id: 'blockchain-5', command: 'geth --dev', description: 'Démarrer Geth en mode dev', category: 'Blockchain', tags: ['geth', 'ethereum'] },
  { id: 'blockchain-6', command: 'hardhat compile', description: 'Compiler avec Hardhat', category: 'Blockchain', tags: ['hardhat', 'compile'] },
  { id: 'blockchain-7', command: 'hardhat test', description: 'Tester avec Hardhat', category: 'Blockchain', tags: ['hardhat', 'test'] },
  { id: 'blockchain-8', command: 'web3.eth.getBalance(address)', description: 'Vérifier le solde Ethereum', category: 'Blockchain', tags: ['web3', 'balance'] },
  { id: 'blockchain-9', command: 'solc --bin contract.sol', description: 'Compiler Solidity', category: 'Blockchain', tags: ['solidity', 'compile'] },
  { id: 'blockchain-10', command: 'brownie compile', description: 'Compiler avec Brownie', category: 'Blockchain', tags: ['brownie', 'compile'] },
  { id: 'blockchain-11', command: 'anchor build', description: 'Construire un projet Anchor', category: 'Blockchain', tags: ['anchor', 'solana'] },
  { id: 'blockchain-12', command: 'solana-test-validator', description: 'Démarrer validateur Solana local', category: 'Blockchain', tags: ['solana', 'validator'] },
  { id: 'blockchain-13', command: 'cargo test-bpf', description: 'Tester programmes Solana', category: 'Blockchain', tags: ['solana', 'test'] },
  { id: 'blockchain-14', command: 'npm install ethers', description: 'Installer Ethers.js', category: 'Blockchain', tags: ['ethers', 'library'] },
  { id: 'blockchain-15', command: 'web3.js', description: 'Utiliser Web3.js', category: 'Blockchain', tags: ['web3', 'library'] },

  // Gaming - Avancé
  { id: 'gaming-1', command: 'unity', description: 'Démarrer Unity Editor', category: 'Gaming', tags: ['unity', 'editor'] },
  { id: 'gaming-2', command: 'unreal', description: 'Démarrer Unreal Engine', category: 'Gaming', tags: ['unreal', 'engine'] },
  { id: 'gaming-3', command: 'godot', description: 'Démarrer Godot Engine', category: 'Gaming', tags: ['godot', 'engine'] },
  { id: 'gaming-4', command: 'npm install three', description: 'Installer Three.js', category: 'Gaming', tags: ['threejs', '3d'] },
  { id: 'gaming-5', command: 'npm install babylonjs', description: 'Installer Babylon.js', category: 'Gaming', tags: ['babylonjs', '3d'] },
  { id: 'gaming-6', command: 'npm install phaser', description: 'Installer Phaser', category: 'Gaming', tags: ['phaser', '2d'] },
  { id: 'gaming-7', command: 'steamcmd +login anonymous', description: 'Se connecter à SteamCMD', category: 'Gaming', tags: ['steamcmd', 'server'] },
  { id: 'gaming-8', command: 'srcds -game csgo', description: 'Démarrer serveur CS:GO', category: 'Gaming', tags: ['srcds', 'server'] },
  { id: 'gaming-9', command: 'minecraft-server.jar', description: 'Démarrer serveur Minecraft', category: 'Gaming', tags: ['minecraft', 'server'] },
  { id: 'gaming-10', command: 'npm install pixi.js', description: 'Installer Pixi.js', category: 'Gaming', tags: ['pixijs', '2d'] },
  { id: 'gaming-11', command: 'npm install matter-js', description: 'Installer Matter.js physics', category: 'Gaming', tags: ['matterjs', 'physics'] },
  { id: 'gaming-12', command: 'blender', description: 'Démarrer Blender', category: 'Gaming', tags: ['blender', '3d'] },
  { id: 'gaming-13', command: 'npm install aframe', description: 'Installer A-Frame VR', category: 'Gaming', tags: ['aframe', 'vr'] },
  { id: 'gaming-14', command: 'npm install cannon-es', description: 'Installer Cannon.js physics', category: 'Gaming', tags: ['cannonjs', 'physics'] },
  { id: 'gaming-15', command: 'gdevelop', description: 'Démarrer GDevelop', category: 'Gaming', tags: ['gdevelop', 'no-code'] }
];

// Ajout de catégories supplémentaires pour les types
export const CATEGORIES = [
  'All',
  'Git',
  'Docker', 
  'Laravel',
  'Linux',
  'Django',
  'Node',
  'React',
  'Kubernetes',
  'SQL',
  'AWS',
  'Go',
  'Rust',
  'Vue',
  'Angular',
  'Rails',
  'Symfony',
  'Flutter',
  'Swift',
  'Kotlin',
  'DevOps',
  'Monitoring',
  'Security',
  'ML',
  'Blockchain',
  'Gaming'
] as const;
